---
- hosts: localhost
  connection: local
  become: true

- hosts: localhost
  name: Obtain matrix account info.
  vars_prompt:
    - name: home_server
      prompt: 'Enter your home server URL inclusing https:// :'

    - name: default_room
      prompt: 'Enter the room id !something:youtdomain.com :'
      
    - name: token
      prompt: What is your account token? 

  tasks:
    - include: tasks/packages.yml
    - include: tasks/matrix_notify.yml
    - include: tasks/add_sshrc.yaml