---
- hosts: localhost
  connection: local
  become: true

- name: Obtain matrix account info.
  vars_prompt:
    - name: home_server
      prompt: Enter the API key

    - name: default_room
      prompt: What is your password?
      
    - name: token
      prompt: What is your password?

  tasks:
    - include: tasks/packages.yml
    # - include: tasks/matrix_notify.yml