- name: Adding matrix log to sshrc
  blockinfile:
    path: /etc/ssh/sshrc
    block: |
      #!/bin/sh
      ip="$(echo "$SSH_CONNECTION" | cut -d " " -f 1)"
      echo $USER@$(hostname) logged in from $ip at $(date +%H:%M:%S) | bash /opt/logToMatrix --homeserver={{ home_server }} --token={{ token }} --room=\{{ default_room }} -
    create: yes
