- name: Installing matrix.sh
  git:
    repo: https://github.com/fabianonline/matrix.sh.git
    dest: /tmp/matrix.sh/

- name: Moving matrix.sh into /usr/local/bin/
  copy:
    src: /tmp/matrix.sh/matrix.sh
    dest: /opt/logToMatrix
    owner: root
    group: root
    mode: u=rwx,g=rx,o=xr
    backup: no

- name: Create bash alias
  lineinfile:
    path: /etc/bash.bashrc
    line: alias matrixLog='bash /opt/logToMatrix --homeserver={{ home_server }} --token={{ token }} --room=\{{ default_room }} -'
    create: yes